# Generated by Django 6.0.6 on 2026-07-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="课程标题")),
                (
                    "cover_image",
                    models.CharField(max_length=500, verbose_name="课程封面"),
                ),
                ("summary", models.TextField(verbose_name="简介")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="价格"
                    ),
                ),
                (
                    "original_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="原价"
                    ),
                ),
                ("instructor", models.CharField(max_length=100, verbose_name="讲师")),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1, max_digits=3, verbose_name="评分"
                    ),
                ),
                (
                    "highlights",
                    models.TextField(
                        help_text="用于展示课程的特色亮点，换行分隔多个亮点",
                        verbose_name="课程亮点",
                    ),
                ),
                (
                    "header_image",
                    models.CharField(max_length=500, verbose_name="课程首图"),
                ),
                (
                    "detail_image",
                    models.CharField(max_length=500, verbose_name="课程详情图"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "AI 编程课",
                "verbose_name_plural": "AI 编程课",
                "db_table": "course",
            },
        ),
    ]
